"""Changed affected_products, suspected_owning_team, and suspected_affected_components to ARRAY(String)

Revision ID: b4e9ce414cb8
Revises: 2602ce9136ef
Create Date: 2024-07-16 23:21:55.562687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b4e9ce414cb8'
down_revision: Union[str, None] = '2602ce9136ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_incidents', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('service_incidents', 'message_for_sp',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('service_incidents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('ix_service_incidents_description'), 'service_incidents', ['description'], unique=False)
    op.create_index(op.f('ix_service_incidents_id'), 'service_incidents', ['id'], unique=False)
    op.create_index(op.f('ix_service_incidents_status'), 'service_incidents', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_incidents_status'), table_name='service_incidents')
    op.drop_index(op.f('ix_service_incidents_id'), table_name='service_incidents')
    op.drop_index(op.f('ix_service_incidents_description'), table_name='service_incidents')
    op.alter_column('service_incidents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('service_incidents', 'message_for_sp',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    op.alter_column('service_incidents', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
